name = "SparseArrayKit"
uuid = "a9a3c162-d163-4c15-8926-b8794fbefed2"
authors = ["Jutho Haegeman <jutho.haegeman@ugent.be> and Maarten Van Damme <Maarten.VanDamme@UGent.be>"]
version = "0.2.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
Requires = "1"
TensorOperations = "4"
TupleTools = "1.1"
julia = "1.6 - 1"

[extensions]
SparseArrayKitTensorOperations = "TensorOperations"
SparseArrayKitSparseArrays = "SparseArrays"

[extras]
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[targets]
test = ["Test", "TestExtras", "TensorOperations", "Strided", "Random", "LinearAlgebra", "SparseArrays"]

[weakdeps]
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"